"""empty message

Revision ID: 0073967f619f
Revises: 1440f2e8836e
Create Date: 2023-12-31 12:01:21.330492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0073967f619f'
down_revision = '1440f2e8836e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
