"""empty message

Revision ID: 807943f0ae1e
Revises: 
Create Date: 2023-12-25 21:20:38.658224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807943f0ae1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habit_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('custom_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')
        batch_op.drop_column('duration')
        batch_op.drop_column('custom_category')
        batch_op.drop_column('type')
        batch_op.drop_column('category')
        batch_op.drop_column('habit_name')

    # ### end Alembic commands ###
